version: "3.2"
services:
  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - type: bind
        source: ./dropbox
        target: /dropbox
      - type: bind
        source: ./config
        target: /config
    ports:
      - 8083:8083
    restart: always
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - URL=computerlab.io
      - SUBDOMAINS=library,
      - VALIDATION=http
      - EMAIL=patrick@computerlab.io
      - ONLY_SUBDOMAINS=true
    volumes:
      - ./letsencrypt-config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: always
  dropbox:
    container_name: dropbox
    image: rbonghi/dropbox:latest
    command: ["--fromDropbox"]
    environment:
      DROPBOX_TOKEN: "${DROPBOX_APP_TOKEN}"
      PYTHONUNBUFFERED: 1
    volumes:
      - type: bind
        source: ./dropbox
        target: /dropbox
    restart: always

