version: "3.2"
services:
  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - ./kbfs:/kbfs:shared
      - ./config:/config
    ports:
      - 8083:8083
    restart: always
  keybase:
    image: waldner/keybase:2
    container_name: keybase
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse:/dev/fuse"
    security_opt:
      - "apparmor:unconfined"
    environment:
      - KEYBASE_ALLOW_ROOT=1
      - KEYBASE_USER=${KEYBASE_USER}
      - KEYBASE_PAPERKEY=${KEYBASE_PAPERKEY}
      - KEYBASE_KBFS_MOUNT=/kbfs
      - UID=1000
      - TZ=${TZ}
    restart: always
    volumes:
    volumes:
      - ./kbfs:/kbfs:shared
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - URL=${URL}
      - SUBDOMAINS=${SUBDOMAINS}
      - VALIDATION=http
      - EMAIL={EMAIL}
      - ONLY_SUBDOMAINS=true
    volumes:
      - ./letsencrypt-config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: always
